//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empno { get; set; }
        public string empname { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<double> hra { get; set; }
        public Nullable<double> pf { get; set; }
        public Nullable<double> grosssalary { get; set; }
        public Nullable<int> deptno { get; set; }
        public Nullable<double> tax { get; set; }
    }
}
